#!/usr/bin/env ruby 
require 'readline'
require 'lib/indextank_client'

@apiurl = nil
@idxname = nil
@api = nil
@index = nil
@data = {}



def command(line)
    args = line.split
    case args[0]
    when "url"
        @apiurl = args[1]
        @api = IndexTank::ApiClient.new @apiurl
        @data['api'] = @api
        printf "api url set to %s\n", @apiurl
    when "list"
        @api.list_indexes.each {|x| puts x.name}
    when "index"
        if !args[1]
            puts @idxname
        else
            @idxname = args[1]
            @index = @api.get_index @idxname
            @data['index'] = @index
            printf "index set to %s\n", @idxname
        end
    when "search"
        results = @index.search args[1..args.length].join ' '
        printf "%s results in %s seconds\n", results['matches'], results['search_time']
        results['results'].each {|doc|
            docid = doc['docid']
            printf "docid: #{docid}\n" 
        }
    when "add"
        if @index == nil
            puts 'set an index first'
        else
           if !args[1]
               docid = Readline.readline('enter docid (blank to abort):', true)
           else
               docid = args[1]
           end
           if docid.strip != ''
               doc = {}
               while true
                   field = Readline.readline('field name (or blank to end): ', true)
                   if field.strip == '' 
                       break
                   end
                   value = Readline.readline('field value: ', true)
                   doc[field] = value
               end
               @index.add_document(docid, doc)
               printf("added %s\n", docid)
           end
        end
    when "help"
        printf "possible commands are:\n\nurl [url] sets the api url\nlist lists all indexes\nindex [index name] sets the index name \
        \nsearch [query] searches the current index\nadd [docid] creates a new document\nquit exits this shell\n\n"

    else
        puts 'no such command, try "help"'
    end
end

if File.exists? '.console'
    @data = Marshal.load File.open('.console')
    @index = @data['index']
    @api = @data['api']
    if @index
        @idxname = @index.name
    end
end

while line = Readline.readline('> ', true) and line != 'quit'
    begin
        command line
        f = File.open '.console', 'w'
        Marshal.dump(@data, f)
        f.close
    rescue Exception => e
        puts e
    end
end

